# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:03
from __future__ import unicode_literals

import contactoApp.modelsC
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoRecursosHumanos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('puesto', models.CharField(max_length=60)),
                ('bio', models.TextField()),
                ('foto', models.ImageField(upload_to=contactoApp.modelsC.path_and_rename_foto)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
