# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 23:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0003_contactorecursoshumanos_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoingenia',
            old_name='correo',
            new_name='email',
        ),
    ]
