# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0004_auto_20160713_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoingenia',
            name='mensaje_home',
            field=models.TextField(default='Hola'),
            preserve_default=False,
        ),
    ]
