# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('contendio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('sueldo', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('abierta', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True)),
            ],
        ),
        migrations.AddField(
            model_name='requisito',
            name='requisito_de',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacantesApp.Vacante'),
        ),
    ]
