# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:37
from __future__ import unicode_literals

import contactoApp.modelsC
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacantesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoAplicante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=14)),
                ('cv', models.FileField(blank=True, upload_to=contactoApp.modelsC.path_and_rename_CV)),
                ('aplica_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacantesApp.Vacante')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoIngenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_compania', models.CharField(default='Ingenia', max_length=30)),
                ('direccion', models.CharField(default=' Anatole France 311 - Polanco, Mexico D.F. ', max_length=140)),
                ('telefono', models.CharField(default='+51 (55) 50 2209 0000', max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactoInteresado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
