# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0005_contactoingenia_mensaje_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoaplicante',
            old_name='nombre',
            new_name='nombre_aplicante',
        ),
    ]
