# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0006_auto_20160721_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoaplicante',
            old_name='nombre_aplicante',
            new_name='nombre_completo',
        ),
        migrations.RenameField(
            model_name='contactoingenia',
            old_name='email',
            new_name='correo_electronico',
        ),
    ]
