# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 16:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactoApp', '0007_auto_20160721_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoingenia',
            old_name='correo_electronico',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contactointeresado',
            old_name='email',
            new_name='correo_electronico',
        ),
    ]
