# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import homeApp.modelsH


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosyPrestacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeIngenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('info_1', 'Info 1'), ('info_2', 'Info 2'), ('info_3', 'Info 3')], max_length=40)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('imagen_1', 'Imagen 1'), ('imagen_2', 'Imagen 2'), ('imagen_3', 'Imagen 3')], max_length=50)),
                ('imagen', models.ImageField(upload_to=homeApp.modelsH.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=10)),
            ],
        ),
    ]
