# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeApp', '0002_auto_20160713_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoingenia',
            name='seccion',
            field=models.CharField(choices=[('info_1', 'Info 1'), ('info_2', 'Info 2'), ('info_3', 'Info 3')], default='titutlo', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infoingenia',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
