# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0002_auto_20160617_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisito',
            name='vacante_ptr',
        ),
        migrations.AddField(
            model_name='requisito',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisito',
            name='requisito_de',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vacantes.Vacante'),
            preserve_default=False,
        ),
    ]
