# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0004_auto_20160622_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosPrestacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
