# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacantes', '0005_beneficiosprestacione'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeneficiosPrestacione',
        ),
    ]
