# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import ingeniaApp.modelsI


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngeniaImagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('imagen_intro', 'Imagen Intro'), ('imagen_1', 'Imagen Pilar 1'), ('imagen_2', 'Imagen Pilar 2'), ('imagen_3', 'Imagen Pilar 3')], max_length=50)),
                ('imagen', models.ImageField(upload_to=ingeniaApp.modelsI.path_and_rename)),
            ],
        ),
        migrations.CreateModel(
            name='IngeniaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('info_intro', 'Intro'), ('info_a1', 'Adicional 1'), ('info_p1', 'Pilar 1'), ('info_p2', 'Pilar 2'), ('info_p3', 'Pilar 3'), ('info_a2', 'Adicional 2')], max_length=40)),
                ('titulo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
