# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import info_base.modelsIB


class Migration(migrations.Migration):

    dependencies = [
        ('info_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiosyPrestacione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeIngenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('home_intro', 'Home Intro'), ('home_quienes_somos', 'Home Quienes Somos'), ('home_por_que_ingenia', 'Home Por Que Ingenia')], max_length=40)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('imagen_intro', 'Imagen Intro'), ('imagen_nuestros_proyectos', 'Imagen Algunos de Nuestros Projectos'), ('imagen_sketch_servicio', 'Imagen Sketch Servicio')], max_length=50)),
                ('imagen', models.ImageField(upload_to=info_base.modelsIB.path_and_rename)),
            ],
        ),
        migrations.DeleteModel(
            name='infoIngenia',
        ),
    ]
